IdentityManager/Controllers/AccessCheckerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityManager.Controllers {
    [Authorize]
    public class AccessCheckerController : Controller {
        //All requests (including Anon)
        [AllowAnonymous] // overwites parent
        public IActionResult AllAccess() {
            return View();
        }

        [Authorize]
        //All Logged in users
        public IActionResult AuthorizedAccess() {
            return View();
        }

        //Users of User Role
        [Authorize(Roles = "User")]
        public IActionResult UserAccess() {
            return View();
        }

        //Users Or Admins User Role
        [Authorize(Roles = "User,Admin")]
        public IActionResult UserOrAdminAccess() {
            return View();
        }

        //Users AND Admins User Role
        [Authorize(Policy = "UserAndAdmin")]
        public IActionResult UserANDAdminAccess() {
            return View();
        }

        //Users of Admin Role
        [Authorize(Policy = "Admin")]
        public IActionResult AdminAccess() {
            return View();
        }

        //Admin Role / Create Claim
        [Authorize(Policy = "AdminWithCreateClaim")]
        public IActionResult Admin_Create_Access() {
            return View();
        }
        //Admin Role / Create Edit and Delete
        [Authorize(Policy = "AdminWithCreateEditDeleteClaim")]

        public IActionResult Admin_Create_Edit_Delete_Access() {
            return View();
        }

        //Admin Role / Create Edit and Delete, OR Super Admin
        [Authorize(Policy = "AdminWithCreateEditDeleteClaimOrSuperAdminRole")]

        public IActionResult Admin_Create_Edit_Delete_Access_SuperAdmin() {
            return View();
        }

    }
}

IdentityManager/Controllers/RolesController.cs
using IdentityManager.Data;
using IdentityManager.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityManager.Controllers {
    public class RolesController : Controller {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(ApplicationDbContext dbContext, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager) {
            this._dbContext = dbContext;
            this._userManager = userManager;
            this._roleManager = roleManager;
        }
        public IActionResult Index() {
            var roles = _dbContext.Roles.ToList();
            return View(roles);
        }

        [HttpGet]
        public IActionResult Upsert(string id) {
            if (string.IsNullOrEmpty(id)) {
                //insert
                return View();
            } else {
                //update
                var role = _dbContext.Roles.FirstOrDefault(r => r.Id == id);
                return View(role);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(IdentityRole role) {


            if (string.IsNullOrEmpty(role.Id)) {
                if (await _roleManager.RoleExistsAsync(role.Name)) {
                    TempData[SD.Error] = "Role Already Exists";
                    return RedirectToAction(nameof(Index));
                }
                await _roleManager.CreateAsync(new IdentityRole() { Name = role.Name });
                TempData[SD.Success] = "Role Created Successfully";


            } else {
                //this should also check to make sure there's no duplicate existing!
                var objFromDb = _dbContext.Roles.FirstOrDefault(r => r.Id == role.Id);
                if (objFromDb == null) {
                    TempData[SD.Error] = "Role Not Found";

                    RedirectToAction(nameof(Index));
                }

                objFromDb.Name = role.Name;
                objFromDb.NormalizedName = role.Name.ToUpper();

                TempData[SD.Success] = "Role Updated Successfully";

                var result = await _roleManager.UpdateAsync(objFromDb);
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpPost]
        public async Task<IActionResult> Delete(string id) {
            var objFromDb = _dbContext.Roles.FirstOrDefault(r => r.Id == id);
            var userAssociatedRoles = _dbContext.UserRoles.Where(r => r.RoleId == id).Count();

            if (objFromDb == null) {
                //role not found
                TempData[SD.Error] = "Role not found!";

                return RedirectToAction(nameof(Index));
            }

            if (userAssociatedRoles > 0) {
                //error (toadd for toast)
                TempData[SD.Error] = "Useres currently assigned to role!";

                return RedirectToAction(nameof(Index));

            }

            var result = await _roleManager.DeleteAsync(objFromDb);
            TempData[SD.Success] = "Role Deleted Successfully";

            return RedirectToAction(nameof(Index));

        }


    }
}

IdentityManager/Controllers/UserController.cs
using IdentityManager.Data;
using IdentityManager.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace IdentityManager.Controllers {
    public class UserController : Controller {
        private readonly ApplicationDbContext _dbContext;
        private readonly UserManager<IdentityUser> _userManager;

        public UserController(ApplicationDbContext dbContext, UserManager<IdentityUser> userManager) {
            this._dbContext = dbContext;
            this._userManager = userManager;
        }
        public IActionResult Index() {
            var users = _dbContext.ApplicationUsers.ToList();
            var userRoles = _dbContext.UserRoles.ToList();
            var roles = _dbContext.Roles.ToList();

            foreach (var user in users) {
                var role = userRoles.FirstOrDefault(u => u.UserId == user.Id);
                if (role == null) {
                    user.Role = "None";
                } else {
                    user.Role = roles.FirstOrDefault(u => u.Id == role.RoleId).Name;
                }

            }


            return View(users);
        }

        [HttpGet]
        public IActionResult Edit(string id) {
            var objFromDb = _dbContext.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (objFromDb == null) {
                return NotFound();
            }

            var userRoles = _dbContext.UserRoles.ToList();
            var roles = _dbContext.Roles.ToList();
            var role = userRoles.FirstOrDefault(u => u.UserId == objFromDb.Id);

            if (role != null) {
                objFromDb.RoleId = roles.FirstOrDefault(u => u.Id == role.RoleId).Id;
            }

            objFromDb.RoleList = _dbContext.Roles.Select(u => new SelectListItem { Text = u.Name, Value = u.Id });



            return View(objFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser user) {
            if (!ModelState.IsValid) {
                user.RoleList = _dbContext.Roles.Select(u => new SelectListItem { Text = u.Name, Value = u.Id });
                return View(user);
            }
            var objFromDb = _dbContext.ApplicationUsers.FirstOrDefault(u => u.Id == user.Id);
            if (objFromDb == null) {
                return NotFound();
            }

            var userRole = _dbContext.UserRoles.FirstOrDefault(r => r.UserId == user.Id);
            if (userRole != null) {
                var prevRoleNme = _dbContext.Roles.Where(u => u.Id == userRole.RoleId).Select(r => r.Name).FirstOrDefault();
                await _userManager.RemoveFromRoleAsync(objFromDb, prevRoleNme);
            }
            await _userManager.AddToRoleAsync(objFromDb, _dbContext.Roles.FirstOrDefault(u => u.Id == user.RoleId).Name);
            objFromDb.Name = user.Name;
            _dbContext.SaveChanges();

            TempData[SD.Success] = "User updated successfully!";

            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<IActionResult> LockUnlock(string id) {
            var objFromDb = _dbContext.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (objFromDb == null) {
                TempData[SD.Error] = "User Not Found";
                return NotFound();
            }

            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now) {
                //user is locked
                objFromDb.LockoutEnd = DateTime.Now;
                TempData[SD.Success] = "User account unlocked";
            } else {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(100);
                TempData[SD.Success] = "User account locked";
            }
            _dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id) {
            var objFromDb = _dbContext.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if (objFromDb == null) {
                TempData[SD.Error] = "User not found!";
                return RedirectToAction(nameof(Index));
            }

            _dbContext.ApplicationUsers.Remove(objFromDb);
            _dbContext.SaveChanges();
            TempData[SD.Success] = "User Deleted";


            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> ManageUserClaims(string userId) {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null) {
                TempData[SD.Error] = "User Not Found";
                return NotFound();
            }
            var existingCliams = await _userManager.GetClaimsAsync(user);

            var model = new UserClaimsViewModel() { UserId = userId };
            foreach (var claim in ClaimStore.claimsList) {
                var userClaim = new UserClaim() {
                    ClaimType = claim.Type,
                    IsSelected = existingCliams.Any(c => c.Type == claim.Type)
                };
                model.Claims.Add(userClaim);
            }
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageUserClaims(UserClaimsViewModel model) {
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) {
                TempData[SD.Error] = "User Not Found";
                return NotFound();
            }

            var existingClaims = await _userManager.GetClaimsAsync(user);            
            if (!(await _userManager.RemoveClaimsAsync(user, existingClaims)).Succeeded) {
                TempData[SD.Error] = "Error Updating Claims";
                return View(model);
            }

            var result = await _userManager.AddClaimsAsync(user, model.Claims.Where(c=>c.IsSelected).Select(c=> new Claim(c.ClaimType, c.IsSelected.ToString())));

            if (result.Succeeded) {
                TempData[SD.Success] = "Claims updated!";
                return RedirectToAction(nameof(Index));
            } else {
                TempData[SD.Error] = "Error Updating Claims";
                return View(model);
            }
        }

    }
}

IdentityManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">*@
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartialCustom" />
                @*<partial name="_LoginPartial" />*@
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Access Checker
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AllAccess">All Access</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AuthorizedAccess">Authorized Access</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="UserAccess">User Access</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="UserOrAdminAccess">User Or Admin Access</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="UserANDAdminAccess">User AND Admin Access</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="AdminAccess">Admin Access</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="Admin_Create_Access">Admin - Create only Claim Access</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="Admin_Create_Edit_Delete_Access">Admin - Create,Edit & Delete Claim Access</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="Admin_Create_Edit_Delete_Access_SuperAdmin">Admin - Create,Edit & Delete Claim Access || Super Admin</a>
                        <a class="dropdown-item" asp-controller="AccessChecker" asp-action="OnlyBhrugen">Only Bhrugen</a>
                    </div>
                </li>

            </ul>
            </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - IdentityManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IdentityManager/Views/Shared/_LoginPartialCustom.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User)) {

        <li class="nav-item">
            <a class="nav-link" href="#">Hello, @UserManager.GetUserName(User)</a>
        </li>
        <li class="nav-item">
            <form id="logoutForm" class="form-inline" asp-controller="Account" asp-action="LogOff" method="post">
                <button class="btn nav-link" type="submit">Logout</button>
            </form>
        </li>
     } else {

        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
        </li>
}
</ul>

IdentityManager/Views/Shared/_Notifications.cshtml
@using IdentityManager.Models

@if (TempData[SD.Success] != null) {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[SD.Success]');
    </script>
}
@if (TempData[SD.Error] != null) {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[SD.Error]');
    </script>
}